-
  branches:
    only:
      - master

  version: 0.2.0.{build}-prerelease

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration: Release

  before_build:
    - ps: nuget restore IF.Lastfm.sln

  build:
    project: IF.Lastfm.sln

  after_test:
    - ps: .nuget\pack.ps1

  artifacts:
    - path: src\IF.Lastfm.Core\bin\Release\IF.Lastfm.Core.dll
      name: IF.Lastfm.Core.dll
    - path: '**\*.nupkg'

  nuget:
    project_feed: true

-
  branches:
    only:
      - release

  version: 0.1.2.{build}

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration: Release

  before_build:
    - ps: nuget restore IF.Lastfm.sln

  build:
    project: IF.Lastfm.sln

  after_test:
    - ps: .nuget\pack.ps1

  artifacts:
    - path: src\IF.Lastfm.Core\bin\Release\IF.Lastfm.Core.dll
      name: IF.Lastfm.Core.dll
    - path: '**\*.nupkg'

  deploy:
    provider: NuGet
    api_key:
      secure: b4Q8KLmOfeQHZNGbTf4OYud3pvi3aR4rKE35dcLHYBTBaQwc9QeoIkDoG13Jpbxs
    artifact: /.*\.nupkg/

  nuget:
    account_feed: true
    project_feed: true
